"""EDA for KuaiRand-Pure -> kb/data/eda_report.md. numpy + stdlib only.

Test split: feature-only statistics, plus ONE labelled check that merely reproduces the composition numbers the
organizers already published (27.1 % / 9.2 % / 63.7 % and oracle nDCG 0.7289) as a harness self-check.
No other test-label statistic is computed here or anywhere else (ADR-0005)."""
import csv, os, sys, collections
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.normpath(os.path.join(HERE, '..', '..', 'kuairand-starter-kit'))
sys.path.insert(0, KIT)
from evaluate import evaluate                                     # noqa: E402
D = os.path.join(KIT, 'KuaiRand-Pure', 'data')
OUT = os.path.join(HERE, 'eda_report.md')
SPLITS = {'train': (20220408, 20220421), 'valid': (20220422, 20220428), 'test': (20220429, 20220508)}
SIG = ['is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate']

# ---------- load ----------
vid2author = {}
with open(f'{D}/video_features_basic_pure.csv') as fh:
    r = csv.DictReader(fh); basic_cols = r.fieldnames
    for row in r: vid2author[row['video_id']] = row['author_id']
with open(f'{D}/user_features_pure.csv') as fh:
    r = csv.DictReader(fh); user_cols = r.fieldnames; n_user_rows = sum(1 for _ in r)
with open(f'{D}/video_features_statistic_pure.csv') as fh:
    stat_cols = csv.DictReader(fh).fieldnames

rows = {k: [] for k in SPLITS}                     # (user, video, date, hour, tab, y, play, dur, sigs, is_rand)
for f in ('log_standard_4_08_to_4_21_pure.csv', 'log_standard_4_22_to_5_08_pure.csv'):
    with open(f'{D}/{f}') as fh:
        for r in csv.DictReader(fh):
            d = int(r['date'])
            for name, (lo, hi) in SPLITS.items():
                if lo <= d <= hi:
                    rows[name].append((r['user_id'], r['video_id'], d, int(r['hourmin']) // 100, r['tab'],
                                       int(r['long_view']), int(r['play_time_ms']), int(r['duration_ms']),
                                       tuple(int(r[s]) for s in SIG), int(r['is_rand'])))
                    break
n_random = sum(1 for _ in open(f'{D}/log_random_4_22_to_5_08_pure.csv')) - 1

md = []
P = md.append
def pct(a, b): return f'{100.0 * a / b:.1f} %'
def q(xs, ps=(10, 50, 90)): return ', '.join(f'p{p}={np.percentile(xs, p):.0f}' for p in ps)

P('# KuaiRand-Pure — measured data facts\n')
P(f'Generated by `kb/data/eda.py`. Files: `{", ".join(sorted(os.listdir(D)))}`.\n')
P('## Files and columns')
P(f'- `user_features_pure.csv`: {n_user_rows:,} users; columns: `{", ".join(user_cols)}`')
P(f'- `video_features_basic_pure.csv`: {len(vid2author):,} videos; columns: `{", ".join(basic_cols)}`')
P(f'- `video_features_statistic_pure.csv`: columns: `{", ".join(stat_cols)}` — whole-month averages, **leaky**, unused')
P(f'- `log_random_4_22_to_5_08_pure.csv`: {n_random:,} rows of random exposure (dates overlap valid + test)\n')

# ---------- per-split basics ----------
P('## Split sizes and per-user impression counts')
P('| split | rows | users | videos | authors | impressions/user mean | p10 / p50 / p90 | max |')
P('|---|---|---|---|---|---|---|---|')
per_user = {}
for name, rws in rows.items():
    c = collections.Counter(x[0] for x in rws); per_user[name] = c
    vids = {x[1] for x in rws}; auths = {vid2author.get(v, 'UNK') for v in vids}
    cnt = np.array(list(c.values()))
    P(f'| {name} | {len(rws):,} | {len(c):,} | {len(vids):,} | {len(auths):,} | {cnt.mean():.2f} | '
      f'{np.percentile(cnt,10):.0f} / {np.percentile(cnt,50):.0f} / {np.percentile(cnt,90):.0f} | {cnt.max()} |')
P('')

# ---------- labels: train + valid only ----------
P('## Label statistics (train and valid only)')
P('| split | positive rate | all-negative users | all-positive users | discriminative users | oracle nDCG@5 | oracle primary |')
P('|---|---|---|---|---|---|---|')
for name in ('train', 'valid'):
    rws = rows[name]
    byu = collections.defaultdict(lambda: [0, 0])
    for x in rws: byu[x[0]][0] += x[5]; byu[x[0]][1] += 1
    an = sum(1 for p, n in byu.values() if p == 0); ap = sum(1 for p, n in byu.values() if p == n)
    nu = len(byu); pr = sum(x[5] for x in rws) / len(rws)
    o = evaluate([x[0] for x in rws], [x[5] for x in rws], [float(x[5]) for x in rws])
    P(f'| {name} | {pr:.4f} | {pct(an, nu)} | {pct(ap, nu)} | {pct(nu - an - ap, nu)} | {o["nDCG@5"]:.4f} | {o["primary"]:.4f} |')
P('\nPublished for test (organizers): all-negative 27.1 %, all-positive 9.2 %, discriminative 63.7 %, oracle nDCG@5 0.7289.')
rws = rows['test']
byu = collections.defaultdict(lambda: [0, 0])
for x in rws: byu[x[0]][0] += x[5]; byu[x[0]][1] += 1
an = sum(1 for p, n in byu.values() if p == 0); ap = sum(1 for p, n in byu.values() if p == n); nu = len(byu)
o = evaluate([x[0] for x in rws], [x[5] for x in rws], [float(x[5]) for x in rws])
P(f'Harness self-check reproduces them: {pct(an, nu)} / {pct(ap, nu)} / {pct(nu - an - ap, nu)}, oracle nDCG@5 {o["nDCG@5"]:.4f}. '
  f'(This is the only test-label computation in the project.)\n')

# ---------- label definition ----------
tv = rows['train'] + rows['valid']
agree = sum(1 for x in tv if x[5] == int(x[6] >= min(x[7], 18000)))
P('## Label definition check')
P(f'`long_view == (play_time_ms >= min(duration_ms, 18000))` holds on {pct(agree, len(tv))} of train+valid rows '
  f'({len(tv) - agree:,} exceptions).')
comp = sum(1 for x in tv if x[6] >= x[7]); P(f'Completed plays (play_time >= duration): {pct(comp, len(tv))} of rows — the censoring the CWM paper models.')
short = sum(1 for x in tv if x[7] <= 18000); P(f'Rows whose video is <= 18 s (label = "watched to the end"): {pct(short, len(tv))}.\n')

# ---------- drift ----------
P('## Drift by date (train + valid labels; test rows only)')
P('| date | split | rows | positive rate |'); P('|---|---|---|---|')
for name in ('train', 'valid', 'test'):
    byd = collections.defaultdict(lambda: [0, 0])
    for x in rows[name]: byd[x[2]][0] += 1; byd[x[2]][1] += x[5]
    for d in sorted(byd):
        n, p = byd[d]
        P(f'| {d} | {name} | {n:,} | {"-" if name == "test" else f"{p / n:.4f}"} |')
P('')

# ---------- cold start ----------
P('## Cold start relative to train')
tr_users = set(per_user['train']); tr_vids = {x[1] for x in rows['train']}; tr_auth = {vid2author.get(v, 'UNK') for v in tr_vids}
P('| split | rows with unseen user | rows with unseen video | rows with unseen author | users with 0 train rows |'); P('|---|---|---|---|---|')
for name in ('valid', 'test'):
    rws = rows[name]; us = set(per_user[name])
    P(f'| {name} | {pct(sum(1 for x in rws if x[0] not in tr_users), len(rws))} | '
      f'{pct(sum(1 for x in rws if x[1] not in tr_vids), len(rws))} | '
      f'{pct(sum(1 for x in rws if vid2author.get(x[1], "UNK") not in tr_auth), len(rws))} | '
      f'{pct(sum(1 for u in us if u not in tr_users), len(us))} |')
hist = [per_user['train'].get(u, 0) for u in per_user['valid']]
P(f'\nTrain history depth for valid users: mean {np.mean(hist):.0f}, {q(hist)} rows.\n')

# ---------- duplicates ----------
P('## Repeated (user, video) pairs')
for name in ('valid', 'test'):
    c = collections.Counter((x[0], x[1]) for x in rows[name])
    rep = sum(n for n in c.values() if n > 1)
    P(f'- {name}: {pct(rep, len(rows[name]))} of rows belong to a repeated pair; max repeats {max(c.values())}. '
      f'(Organizers: test 3.06 %, max 12.)')
P('')

# ---------- duration ----------
P('## long_view rate by duration bucket (train; 10 train-quantile buckets as in data.py)')
durs = np.array([x[7] for x in rows['train']]); edges = np.quantile(durs, np.linspace(0, 1, 11)[1:-1])
bk = np.searchsorted(edges, durs); ys = np.array([x[5] for x in rows['train']])
P('| bucket | duration range (s) | rows | positive rate |'); P('|---|---|---|---|')
lo = 0.0
for b in range(10):
    hi = edges[b] if b < 9 else durs.max(); m = bk == b
    P(f'| {b} | {lo/1000:.1f}–{hi/1000:.1f} | {m.sum():,} | {ys[m].mean():.4f} |'); lo = hi
P('')

# ---------- other signals ----------
P('## Other feedback signals (train)')
ytr = np.array([x[5] for x in rows['train']], dtype=float)
P('| signal | rate | P(long_view=1 | signal=1) | P(signal=1 | long_view=1) | corr with long_view |'); P('|---|---|---|---|---|')
for i, s in enumerate(SIG):
    v = np.array([x[8][i] for x in rows['train']], dtype=float)
    p_lv_s = ytr[v == 1].mean() if v.sum() else float('nan'); p_s_lv = v[ytr == 1].mean()
    P(f'| {s} | {v.mean():.4f} | {p_lv_s:.4f} | {p_s_lv:.4f} | {np.corrcoef(v, ytr)[0,1]:.3f} |')
rnd = sum(x[9] for x in tv); P(f'\n`is_rand` in the standard log: {rnd} rows (should be 0).\n')

# ---------- tab / hour ----------
P('## Context (train)')
bt = collections.defaultdict(lambda: [0, 0])
for x in rows['train']: bt[x[4]][0] += 1; bt[x[4]][1] += x[5]
P('| tab | rows | share | positive rate |'); P('|---|---|---|---|')
for t in sorted(bt, key=lambda t: -bt[t][0]):
    n, p = bt[t]; P(f'| {t} | {n:,} | {pct(n, len(rows["train"]))} | {p / n:.4f} |')
bh = collections.defaultdict(lambda: [0, 0])
for x in rows['train']: bh[x[3]][0] += 1; bh[x[3]][1] += x[5]
P('\nPositive rate by hour of day: ' + ', '.join(f'{h:02d}h {bh[h][1]/bh[h][0]:.3f}' for h in sorted(bh)) + '\n')

open(OUT, 'w').write('\n'.join(md) + '\n')
print(f'wrote {OUT} ({len(md)} lines)')
