"""Generate the complete run inventory from the filesystem (never hand-maintained).

Writes logs/RUNS_INVENTORY.md and evidence/run_inventory.csv covering EVERY
logs/run_*/ directory: dataset, stop reason, iterations, best primary, tokens,
wall-clock, and whether the run completed (summary.json present).
Usage: uv run python tools/audit_runs.py
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def journal_stats(run: Path) -> tuple[int, float]:
    n, best = 0, 0.0
    jp = run / "journal.jsonl"
    if jp.exists():
        for line in jp.read_text().splitlines():
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue
            n += 1
            if r.get("accepted"):
                best = max(best, (r.get("metrics") or {}).get("primary", 0) or 0)
    return n, best


def main() -> None:
    rows = []
    for run in sorted(ROOT.glob("logs/run_*")):
        if not run.is_dir():
            continue
        s = {}
        complete = (run / "summary.json").exists()
        if complete:
            try:
                s = json.loads((run / "summary.json").read_text())
            except json.JSONDecodeError:
                complete = False
        n_records, j_best = journal_stats(run)
        best = (s.get("best_metrics") or {}).get("primary") or j_best or None
        rows.append({
            "run": run.name,
            "dataset": s.get("dataset", "pure"),
            "complete": complete,
            "stop_reason": s.get("stop_reason", "(no summary — incomplete/aborted)"),
            "iterations": s.get("iterations", n_records - 1 if n_records else 0),
            "journal_records": n_records,
            "best_primary": round(best, 6) if best else None,
            "tokens_total": s.get("tokens_total"),
            "wall_s": int(s.get("wall_s", 0)) or None,
        })
    csv_path = ROOT / "evidence/run_inventory.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    total_tokens = sum(r["tokens_total"] or 0 for r in rows)
    total_wall = sum(r["wall_s"] or 0 for r in rows)
    complete_n = sum(1 for r in rows if r["complete"])
    md = [
        "# Complete run inventory (machine-generated by tools/audit_runs.py — do not edit)",
        "",
        f"Runs found: **{len(rows)}** ({complete_n} completed with summaries, "
        f"{len(rows) - complete_n} incomplete/aborted — disclosed regardless).",
        f"Aggregate (lower bound, completed runs): **{total_tokens:,} LLM tokens**, "
        f"**{total_wall/3600:.1f} run-hours** wall-clock.",
        "",
        "| run | dataset | complete | stop | iters | best primary | tokens | wall s |",
        "|---|---|---|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        md.append(
            f"| {r['run']} | {r['dataset']} | {'y' if r['complete'] else 'NO'} | "
            f"{r['stop_reason']} | {r['iterations']} | {r['best_primary'] or '—'} | "
            f"{r['tokens_total'] or '—'} | {r['wall_s'] or '—'} |")
    (ROOT / "logs/RUNS_INVENTORY.md").write_text("\n".join(md) + "\n")
    print(f"{len(rows)} runs -> logs/RUNS_INVENTORY.md + evidence/run_inventory.csv")
    print(f"aggregate: {total_tokens:,} tokens, {total_wall/3600:.1f} h")


if __name__ == "__main__":
    main()
